name: Sync to Hugging Face Space
on:
  push:
    # 1. TWEAK: Tell GitHub to only listen to your lightweight branch
    branches: [hf-deployment] 
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
          
      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git push --force https://parvv-24:$HF_TOKEN@huggingface.co/spaces/parvv-24/CoughGPT HEAD:main
